<?php

/*
 * Copyright (C) 2015-2024 Deciso B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/* Language support, autogenerated file */
echo gettext('ARC');
echo gettext('Accounts');
echo gettext('Action');
echo gettext('Announcements');
echo gettext('Apcupsd');
echo gettext('BIOS');
echo gettext('Backend State');
echo gettext('Battery date');
echo gettext('Battery is charging');
echo gettext('Battery is discharging');
echo gettext('Battery level');
echo gettext('Battery needs to be replaced');
echo gettext('Battery runtime');
echo gettext('Battery status');
echo gettext('Battery voltage');
echo gettext('Bytes In');
echo gettext('Bytes Out');
echo gettext('CARP IP');
echo gettext('CARP Status');
echo gettext('CPU');
echo gettext('CPU thermal sensors often measure the same temperature for each CPU.');
echo gettext('Caddy Domains');
echo gettext('Caddy does not manage any domains.');
echo gettext('Caddy is disabled or not configured.');
echo gettext('Certificates');
echo gettext('Click to track this rule in Live View');
echo gettext('Client');
echo gettext('Clients');
echo gettext('Collisions');
echo gettext('Connect');
echo gettext('Could not fetch data');
echo gettext('Count');
echo gettext('Current IP');
echo gettext('Current date/time');
echo gettext('Custom');
echo gettext('DMI Data');
echo gettext('DNS Name');
echo gettext('Deciso Hardware Information');
echo gettext('Destination');
echo gettext('Device');
echo gettext('Directory');
echo gettext('Disabled');
echo gettext('Disconnect');
echo gettext('Disk');
echo gettext('DynDNS service is not running');
echo gettext('Dynamic DNS');
echo gettext('Enabled');
echo gettext('Error fetching SMART info for device');
echo gettext('Error fetching disk list');
echo gettext('Errors In');
echo gettext('Errors Out');
echo gettext('Events');
echo gettext('Exit Node');
echo gettext('Expired');
echo gettext('Expired on');
echo gettext('Expires in');
echo gettext('FIFO');
echo gettext('Failed');
echo gettext('Failed due to battery capacity (BT)');
echo gettext('Failed due to overload (NG)');
echo gettext('Family');
echo gettext('File');
echo gettext('Filesystem');
echo gettext('Firewall');
echo gettext('Firewall States');
echo gettext('Forced Shutdown');
echo gettext('Free');
echo gettext('Gateways');
echo gettext('Graphs');
echo gettext('Hidden Certificates');
echo gettext('High battery');
echo gettext('Host');
echo gettext('Hostnames');
echo gettext('IP Alias');
echo gettext('IPsec Leases');
echo gettext('IPsec Tunnels');
echo gettext('IPsec is currently disabled. Click to configure IPsec.');
echo gettext('Input Power');
echo gettext('Install Time');
echo gettext('Interface');
echo gettext('Interface Statistics');
echo gettext('Interfaces');
echo gettext('Interrupt');
echo gettext('Kill connection');
echo gettext('Label');
echo gettext('Last configuration change');
echo gettext('Last event');
echo gettext('Last heartbeat');
echo gettext('Last rule download');
echo gettext('Line voltage');
echo gettext('Live Log');
echo gettext('Load');
echo gettext('Load average');
echo gettext('Loss');
echo gettext('Low battery');
echo gettext('Manufacturer');
echo gettext('Matched rule');
echo gettext('Mbuf');
echo gettext('Memory');
echo gettext('Message');
echo gettext('Model');
echo gettext('Monit Status');
echo gettext('Monit is disabled or not configured.');
echo gettext('N/A');
echo gettext('NUT');
echo gettext('Name');
echo gettext('Network');
echo gettext('No');
echo gettext('No CARP Interfaces configured. Click to configure CARP.');
echo gettext('No DynDNS account information available');
echo gettext('No Gateways configured. Click to configure gateways.');
echo gettext('No certificates to display.');
echo gettext('No clients connected');
echo gettext('No picture was supplied for this system.');
echo gettext('No results');
echo gettext('No saved WOL addresses');
echo gettext('No services found');
echo gettext('No tunnels connected');
echo gettext('Not connected to any server');
echo gettext('Nut is not returning a status. Click to reconfigure Nut.');
echo gettext('Nut is not started. Click to configure Nut.');
echo gettext('OK');
echo gettext('Offline');
echo gettext('On battery');
echo gettext('On line');
echo gettext('Online');
echo gettext('OpenVPN Client Connections');
echo gettext('OpenVPN Server Connections');
echo gettext('Output Power');
echo gettext('Packets In');
echo gettext('Packets Out');
echo gettext('Peers');
echo gettext('Performing runtime calibration');
echo gettext('Phase1 not configured');
echo gettext('Phase2 disconnected');
echo gettext('Picture');
echo gettext('Platform');
echo gettext('Port');
echo gettext('Power Supply');
echo gettext('Power is off');
echo gettext('Power is on');
echo gettext('Power status could not be fetched. This widget is only applicable to Deciso hardware with dual power supplies.');
echo gettext('Process');
echo gettext('Product Name');
echo gettext('RTT');
echo gettext('RTTd');
echo gettext('Release Date');
echo gettext('Remote NUT Server');
echo gettext('Restart');
echo gettext('Running');
echo gettext('SMART Status');
echo gettext('Self test');
echo gettext('Serial Number');
echo gettext('Server');
echo gettext('Services');
echo gettext('Severity');
echo gettext('Source');
echo gettext('Stale');
echo gettext('Start');
echo gettext('Status');
echo gettext('Status update');
echo gettext('Stop');
echo gettext('Stopped');
echo gettext('Swap');
echo gettext('System');
echo gettext('System Information');
echo gettext('Tailscale');
echo gettext('Tailscale IP');
echo gettext('Tailscale service is not running');
echo gettext('Telemetry status');
echo gettext('Temperature');
echo gettext('There are currently no leases.');
echo gettext('Thermal Sensors');
echo gettext('Thermal sensors not available or not configured.');
echo gettext('This widget only works with the Netclient driver. Click to configure the Netclient driver.');
echo gettext('Time');
echo gettext('Total');
echo gettext('Traffic Graph');
echo gettext('Traffic In');
echo gettext('Traffic Out');
echo gettext('Tunnels');
echo gettext('Type');
echo gettext('UPS Efficiency');
echo gettext('UPS Load');
echo gettext('UPS Model');
echo gettext('UPS Status');
echo gettext('UPS bypass circuit is active');
echo gettext('UPS is boosting voltage');
echo gettext('UPS is offline');
echo gettext('UPS is overloaded');
echo gettext('UPS is trimming voltage');
echo gettext('Unable to contact information feed.');
echo gettext('Updated');
echo gettext('Updates');
echo gettext('Uptime');
echo gettext('Used');
echo gettext('User');
echo gettext('Users');
echo gettext('Valid');
echo gettext('Vendor');
echo gettext('Version');
echo gettext('Versions');
echo gettext('Waiting for data');
echo gettext('WakeOnLan');
echo gettext('Wireguard');
echo gettext('Wireguard is currently disabled. Click to configure Wireguard.');
echo gettext('Yes');
echo gettext('active');
echo gettext('days');
echo gettext('h');
echo gettext('m');
echo gettext('s');
