<?php

/**
 *    Copyright (C) 2015 Deciso B.V.
 *
 *    All rights reserved.
 *
 *    Redistribution and use in source and binary forms, with or without
 *    modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 *    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 *    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *    POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *
 * Language support, autogenerated file
 *
 */
echo gettext('A SSL fingerprint should be a 59 character long hex value.');
echo gettext('ACL');
echo gettext('ACLs');
echo gettext('ARP Table');
echo gettext('Access');
echo gettext('Access Lists');
echo gettext('Actions');
echo gettext('Administration');
echo gettext('Advanced');
echo gettext('Advanced Settings');
echo gettext('Advertisements');
echo gettext('Aliases');
echo gettext('All');
echo gettext('Assignments');
echo gettext('Auth');
echo gettext('Authorities');
echo gettext('Backends');
echo gettext('Backups');
echo gettext('Bandwidth metric should be either bit/s, kbit/s or Mbit/s');
echo gettext('Bandwidth out of range');
echo gettext('Both throttling parameters should either be filled or empty');
echo gettext('Bridge');
echo gettext('Cache');
echo gettext('Captive Portal');
echo gettext('Certificates');
echo gettext('Client Export');
echo gettext('Client Specific Overrides');
echo gettext('Clients');
echo gettext('Commercial Support');
echo gettext('Configuration');
echo gettext('Connection Status');
echo gettext('Counters');
echo gettext('Credentials TTL needs to be an integer value above 0');
echo gettext('Cron');
echo gettext('DHCP');
echo gettext('DHCPv6');
echo gettext('DNS Forwarder');
echo gettext('DNS Resolver');
echo gettext('DNS Tools');
echo gettext('Dashboard');
echo gettext('Debug level needs to be an integer value between 0 and 7');
echo gettext('Defaults');
echo gettext('Description should be a string between 1 and 255 characters');
echo gettext('Description should be a string between 1 and 255 characters.');
echo gettext('Detault Parameters');
echo gettext('Devices');
echo gettext('Diagnostics');
echo gettext('Documentation');
echo gettext('Does not look like a valid cookie name (most special characters are not allowed).');
echo gettext('DynDNS');
echo gettext('Dynamic View');
echo gettext('Enter a description.');
echo gettext('Enter a valid number of logs to save');
echo gettext('Enter valid parameter(s) for the chosen command (Found illegal characters).');
echo gettext('Error Files');
echo gettext('FTP');
echo gettext('FTP Proxy');
echo gettext('FTP Proxy port needs to be an integer value between 1 and 65535');
echo gettext('File content should be in (base64 encoded) zip format');
echo gettext('Fileid should be an internally generated unique number');
echo gettext('Filename should be unique');
echo gettext('Filter');
echo gettext('Filter Reload');
echo gettext('Firewall');
echo gettext('Firmware');
echo gettext('Forward');
echo gettext('Frontends');
echo gettext('GIF');
echo gettext('GPS');
echo gettext('GRE');
echo gettext('Gateways');
echo gettext('General');
echo gettext('Global Parameters');
echo gettext('Group');
echo gettext('Group Status');
echo gettext('Groups');
echo gettext('HAProxy');
echo gettext('Hard timeout, in minutes, must be between 0 (no timeout) and 10080 (a week)');
echo gettext('Health');
echo gettext('Health Checks');
echo gettext('Hello World!');
echo gettext('Help');
echo gettext('High Availability');
echo gettext('History');
echo gettext('ICAP');
echo gettext('ICP port needs to be an integer value between 1 and 65535');
echo gettext('ID should be a number.');
echo gettext('IGMP Proxy');
echo gettext('IPsec');
echo gettext('Idle timeout needs to be an integer value between 1 and 86400');
echo gettext('Idle timeout, in minutes, must be between 0 (no timeout) and 10080 (a week)');
echo gettext('Import');
echo gettext('Insight');
echo gettext('Interfaces');
echo gettext('Intrusion Detection');
echo gettext('L2TP');
echo gettext('LAGG');
echo gettext('Lease Status');
echo gettext('Leases');
echo gettext('License');
echo gettext('Listen address must be a valid IPv4 address');
echo gettext('Listen port needs to be an integer value between 1 and 65535');
echo gettext('Load Balancer');
echo gettext('Lobby');
echo gettext('Log File');
echo gettext('Log Files');
echo gettext('Logging');
echo gettext('Logging Configuration');
echo gettext('Logout');
echo gettext('Lookup');
echo gettext('Lua Scripts');
echo gettext('Maximum number of concurrent FTP sessions needs to be an integer value between 1 and 500');
echo gettext('Maximum number of zones reached');
echo gettext('Miscellaneous');
echo gettext('Mobile Clients');
echo gettext('Monitors');
echo gettext('NAT');
echo gettext('NDP Table');
echo gettext('NPT (IPv6)');
echo gettext('NetFlow');
echo gettext('Network Time');
echo gettext('Normal View');
echo gettext('Normalization');
echo gettext('Notifications');
echo gettext('Number of children needs to be an integer value above 0');
echo gettext('One-to-One');
echo gettext('OpenVPN');
echo gettext('Origin should be regular text of max 30 characters');
echo gettext('Origin should be regular text of max 30 characters.');
echo gettext('Other Types');
echo gettext('Outbound');
echo gettext('Overrides');
echo gettext('Overview');
echo gettext('PPPoE');
echo gettext('PPS');
echo gettext('PPTP');
echo gettext('Packages');
echo gettext('Packet Capture');
echo gettext('Password');
echo gettext('Ping');
echo gettext('Pipe number must be between 1...65535');
echo gettext('Pipes');
echo gettext('Plain View');
echo gettext('Please enter a valid email address.');
echo gettext('Please enter a valid servername, ip address or leave this option blank');
echo gettext('Please enter a valid servername, ip address or leave this option blank.');
echo gettext('Please enter ip addresses or domain names here');
echo gettext('Please enter valid addresses');
echo gettext('Please enter valid mac addresses');
echo gettext('Please enter valid targets (e.g. 192.168.0.1:2055).');
echo gettext('Please provide a valid listen address, i.e. 10.0.0.1:8080 or haproxy.example.com:8999.');
echo gettext('Please provide a valid listen address, i.e. 127.0.0.1:8080 or www.example.com:443. Port range as start-end, i.e. 127.0.0.1:1220-1240.');
echo gettext('Please provide a valid user and password, i.e. user:secret123.');
echo gettext('Please select a valid CA from the list.');
echo gettext('Please select a valid CRL from the list.');
echo gettext('Please select a valid certificate from the list');
echo gettext('Please select a valid certificate from the list.');
echo gettext('Please select a valid pattern matcher algorithm');
echo gettext('Please select a valid rotation');
echo gettext('Please specify a valid hostname.');
echo gettext('Please specify a valid servername or IP address.');
echo gettext('Please specify a valid source address, i.e. 10.0.0.1 or loadbalancer.example.com:50000. Port range as start-end, i.e. 10.0.0.1:50000-60000.');
echo gettext('Please specify a value between 0 and 1024.');
echo gettext('Please specify a value between 0 and 256.');
echo gettext('Please specify a value between 0 and 50.');
echo gettext('Please specify a value between 1 and 100.');
echo gettext('Please specify a value between 1 and 10000.');
echo gettext('Please specify a value between 1 and 128.');
echo gettext('Please specify a value between 1 and 500000.');
echo gettext('Please specify a value between 1 and 65535.');
echo gettext('Please specify a value between 1024 and 1048576.');
echo gettext('Please specify a value between 1024 and 16384.');
echo gettext('Please specify a value between 1024 and 65535.');
echo gettext('Please specify a value between 250 and 1000000.');
echo gettext('Please specify a value between 500 and 100000.');
echo gettext('Please specify a value between 64 and 65535.');
echo gettext('Plugins');
echo gettext('Point-to-Point');
echo gettext('Pool Setup');
echo gettext('Pool Status');
echo gettext('Port Forward');
echo gettext('Power');
echo gettext('Power Off');
echo gettext('Pre-Shared Keys');
echo gettext('Proxy');
echo gettext('Proxy port needs to be an integer value between 1 and 65535');
echo gettext('QinQ');
echo gettext('Queue number must be between 1...65535');
echo gettext('Queues');
echo gettext('RFC 2136');
echo gettext('Reboot');
echo gettext('Related cron not found');
echo gettext('Related cron not found.');
echo gettext('Related item not found');
echo gettext('Related pipe not found');
echo gettext('Related pipe or queue not found');
echo gettext('Related template not found');
echo gettext('Relay');
echo gettext('RemoteACL');
echo gettext('Reporter');
echo gettext('Reporting');
echo gettext('Reverse address must be a valid IPv4 address');
echo gettext('Reverse port needs to be an integer value between 1 and 65535');
echo gettext('Revocation');
echo gettext('Routes');
echo gettext('Rules');
echo gettext('SMART');
echo gettext('SNMP');
echo gettext('SSL Proxy port needs to be an integer value between 1 and 65535');
echo gettext('Schedules');
echo gettext('Security Association Database');
echo gettext('Security Policy Database');
echo gettext('Select a command from the list.');
echo gettext('Server');
echo gettext('Servers');
echo gettext('Service Settings');
echo gettext('Services');
echo gettext('Sessions');
echo gettext('Settings');
echo gettext('Should be a number between 1 and 5 characters followed by either "d", "h", "m", "s" or "ms".');
echo gettext('Should be a number between 1 and 5 characters followed by either "k", "m" or "g".');
echo gettext('Should be a number between 1 and 8 characters, optionally followed by either "d", "h", "m", "s", "ms" or "us".');
echo gettext('Should be a string between 1 and 255 characters.');
echo gettext('Sid should be a number.');
echo gettext('Single-Sign On');
echo gettext('Sockets');
echo gettext('Source address must be a valid IPv4 address');
echo gettext('Specify a maximum object size. (number of MB\'s)');
echo gettext('Specify a positive cache size. (number of MB\'s)');
echo gettext('Specify a positive memory cache size. (number of MB\'s)');
echo gettext('Specify a positive number of first-level subdirectories.');
echo gettext('Specify a positive number of second-level subdirectories.');
echo gettext('Specify the maximum download size (kB).');
echo gettext('Specify the maximum upload size (kB).');
echo gettext('Specify the overall bandwidth for downloads in kilobits per second.');
echo gettext('Specify the per host bandwidth for downloads in kilobits per second.');
echo gettext('States Dump');
echo gettext('States Reset');
echo gettext('States Summary');
echo gettext('Statistics');
echo gettext('Statistics Configuration');
echo gettext('Status');
echo gettext('Status Overview');
echo gettext('Stick Tables');
echo gettext('Summary View');
echo gettext('System');
echo gettext('Template name should be a string between 1 and 255 characters');
echo gettext('Test Port');
echo gettext('Tester');
echo gettext('The filename may only contain letters, digits and one dot (not required).');
echo gettext('The name should contain only alphanumeric characters.');
echo gettext('This does not look like a valid url.');
echo gettext('Tinc');
echo gettext('Traceroute');
echo gettext('Traffic Graph');
echo gettext('Traffic Shaper');
echo gettext('TrafficManagement');
echo gettext('Trust');
echo gettext('Tunables');
echo gettext('Tunnel Settings');
echo gettext('Universal Plug and Play');
echo gettext('Updates');
echo gettext('User Forum');
echo gettext('Users');
echo gettext('VLAN');
echo gettext('VPN');
echo gettext('Value needs to be between 0 and 23; multiple values, ranges, steps and asterisk are supported (ex. 1,2,8 or 0-8).');
echo gettext('Value needs to be between 0 and 59; multiple values, ranges, steps and asterisk are supported (ex. 1,10,20,30 or 1-30).');
echo gettext('Value needs to be between 0 and 7 (Sunday to Sunday), multiple values, ranges, steps and asterisk are supported (ex. 1,2,4 or 0-4).');
echo gettext('Value needs to be between 1 and 12 or JAN to DEC, multiple values, ranges, steps and asterisk are supported (ex. JAN,2,10 or 3-8).');
echo gettext('Value needs to be between 1 and 31; multiple values, ranges, L (last day of month), steps and asterisk are supported (ex. 1,2,8 or 1-28).');
echo gettext('View');
echo gettext('Virtual IPs');
echo gettext('Virtual Server Setup');
echo gettext('Virtual Server Status');
echo gettext('Vouchers');
echo gettext('Wake on LAN');
echo gettext('Web Proxy');
echo gettext('Weight must be between 1...100');
echo gettext('Wireless');
echo gettext('Wizard');
echo gettext('debug level needs to be between 0 (default) and 5 (highest)');
echo gettext('max size needs to be an integer value between 1 and 65535');
echo gettext('menu');
echo gettext('origin should be regular text of max 30 characters');
echo gettext('pfInfo');
echo gettext('pfTables');
echo gettext('pfTop');
echo gettext('please specify a valid email address');
echo gettext('provide a valid sequence for sorting');
echo gettext('queue size should be between 2...100');
echo gettext('the number of sslrtd children needs to be an integer value between 1 and 32');
echo gettext('workAround');
